# Generated by Django 4.2.3 on 2023-08-01 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subdomain_prefix', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$', 'Enter a valid subdomain name.')])),
            ],
        ),
        migrations.CreateModel(
            name='rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('edition', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('development', 'Development'), ('integration', 'Integration'), ('testing', 'Testing'), ('ready', 'Ready'), ('maintainance', 'Maintainance')], max_length=255)),
                ('build_start', models.DateTimeField()),
                ('build_end', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.FloatField(help_text='in Tonnes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rocket')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('launched', 'Launched'), ('postponed', 'Postponed'), ('ready', 'Ready'), ('failed', 'Failed')], max_length=255)),
                ('rockets', models.ManyToManyField(blank=True, to='main.rocket')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
            ],
            options={
                'verbose_name_plural': 'Launches',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
    ]
