# Generated by Django 4.2.3 on 2023-08-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
    ]
